FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:latest

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y git nodejs npm
RUN npm install -g yarn

RUN git clone https://github.com/tngoman/Store-POS ./
RUN rm package.json
COPY . ./
RUN yarn
RUN npx electron-builder -l build
RUN chmod +x dist/linux-unpacked/pos
RUN cat start.sh && chmod +x start.sh
# ENV UDEV=1

CMD /usr/src/app/start.sh