FROM balenalib/%%BALENA_MACHINE_NAME%%-ubuntu:latest

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y git

RUN git clone https://github.com/tngoman/Store-POS ./
RUN npm install
COPY . ./

ENV UDEV=1

CMD start.sh